In [1]:
print("Natasha Cloud project is working 🚀")

Natasha Cloud project is working 🚀

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("../data/wnba_player_gamelogs.csv")

In [4]:
df.head()

,Date,PlayerName,TeamAbbreviation,Opponent,Minutes,PlusMinus,OffPoss,DefPoss,PenaltyOffPoss,PenaltyDefPoss,...,DefFTReboundPct,OffLongMidRangeReboundPct,BlockedLongMidRange,BlockedCorner3,SecondChanceCorner3PctAssisted,Defensive 3 Seconds Violations,3SecondViolations,Clear Path Fouls,Period1Fouls3Minutes,Period3Fouls5Minutes
0,2025-05-16,Kelsey Plum,LVA,GSV,40:00,17.0,80.0,82.0,22.0,19.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2025-05-18,Kelsey Plum,LVA,MIN,34:03,-17.0,66.0,64.0,20.0,12.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2025-05-21,Kelsey Plum,LVA,PHX,40:00,-3.0,82.0,83.0,25.0,20.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2025-05-23,Kelsey Plum,LVA,GSV,36:41,-1.0,73.0,73.0,16.0,15.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2025-05-25,Kelsey Plum,LVA,CHI,36:18,19.0,73.0,72.0,15.0,18.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
natasha_df = df[df["PlayerName"] == "Natasha Cloud"]

In [6]:
natasha_df.head()

,Date,PlayerName,TeamAbbreviation,Opponent,Minutes,PlusMinus,OffPoss,DefPoss,PenaltyOffPoss,PenaltyDefPoss,...,DefFTReboundPct,OffLongMidRangeReboundPct,BlockedLongMidRange,BlockedCorner3,SecondChanceCorner3PctAssisted,Defensive 3 Seconds Violations,3SecondViolations,Clear Path Fouls,Period1Fouls3Minutes,Period3Fouls5Minutes
1018,2025-05-17,Natasha Cloud,1611661313,LVA,32:57,9.0,65.0,65.0,20.0,16.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1019,2025-05-22,Natasha Cloud,1611661313,CHI,26:55,27.0,56.0,55.0,17.0,2.0,...,0.333333,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1020,2025-05-24,Natasha Cloud,1611661313,IND,34:33,13.0,71.0,70.0,14.0,7.0,...,0.500000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1021,2025-05-27,Natasha Cloud,1611661313,GSV,25:01,20.0,52.0,51.0,4.0,10.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1022,2025-05-29,Natasha Cloud,1611661313,GSV,30:01,14.0,59.0,60.0,20.0,12.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
len(natasha_df)

41

In [8]:
natasha_df.columns

Index(['Date', 'PlayerName', 'TeamAbbreviation', 'Opponent', 'Minutes',
       'PlusMinus', 'OffPoss', 'DefPoss', 'PenaltyOffPoss', 'PenaltyDefPoss',
       ...
       'DefFTReboundPct', 'OffLongMidRangeReboundPct', 'BlockedLongMidRange',
       'BlockedCorner3', 'SecondChanceCorner3PctAssisted',
       'Defensive 3 Seconds Violations', '3SecondViolations',
       'Clear Path Fouls', 'Period1Fouls3Minutes', 'Period3Fouls5Minutes'],
      dtype='str', length=243)

In [9]:
natasha_df[[
    "Date",
    "PlayerName",
    "Minutes"
]].head()

            Date     PlayerName Minutes
1018  2025-05-17  Natasha Cloud   32:57
1019  2025-05-22  Natasha Cloud   26:55
1020  2025-05-24  Natasha Cloud   34:33
1021  2025-05-27  Natasha Cloud   25:01
1022  2025-05-29  Natasha Cloud   30:01

In [10]:
natasha_df["Date"].head()

1018    2025-05-17
1019    2025-05-22
1020    2025-05-24
1021    2025-05-27
1022    2025-05-29
Name: Date, dtype: str

In [11]:
natasha_df["Date"].tail()

1054    2025-08-30
1055    2025-09-02
1056    2025-09-05
1057    2025-09-09
1058    2025-09-11
Name: Date, dtype: str

In [12]:
df[df["PlayerName"].str.contains("Cloud", case=False, na=False)]["PlayerName"].unique()

<StringArray>
['Natasha Cloud']
Length: 1, dtype: str

In [13]:
career_df = pd.read_csv("../data/natasha_cloud_career_stats.csv")

In [14]:
career_df

   Season Team  GP  PPG  APG  RPG  SPG   MPG
0    2015  WAS  33  3.6  3.4  1.9  0.7  15.6
1    2016  WAS  34  8.7  5.1  3.6  1.4  27.8
2    2017  WAS  32  8.1  5.3  3.0  1.7  27.0
3    2018  WAS  33  9.1  5.6  3.7  1.5  28.0
4    2019  WAS  34  6.4  5.7  3.5  1.0  26.6

In [15]:
import pandas as pd

df = pd.read_csv("../data/natasha_cloud_game_logs.csv")

print("Dataset loaded!")

Dataset loaded!

In [16]:
df.shape

(327, 27)

In [17]:
df.head()

,MATCH UP,SEASON,DATE,TEAM,OPPONENT,HOME/AWAY,RESULT,MIN,PTS,FGM,...,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PlusMinus
0,"Jun 05, 2015 - WAS @ CON",2015,06/05/2015,WAS,CON,Away,W,16,3,1,...,50.0,0,4,4,3,0,1,0,2,-6
1,"Jun 06, 2015 - WAS vs. NYL",2015,06/06/2015,WAS,NYL,Home,W,15,7,2,...,66.7,0,2,2,3,0,0,3,1,3
2,"Jun 12, 2015 - WAS vs. ATL",2015,06/12/2015,WAS,ATL,Home,L,30,4,1,...,50.0,0,3,3,4,1,1,3,2,-4
3,"Jun 14, 2015 - WAS @ NYL",2015,06/14/2015,WAS,NYL,Away,W,15,0,0,...,0.0,0,2,2,3,0,0,2,5,-16
4,"Jun 19, 2015 - WAS vs. TUL",2015,06/19/2015,WAS,TUL,Home,L,11,0,0,...,0.0,0,0,0,3,2,0,1,1,3

In [18]:
df.columns

Index(['MATCH UP', 'SEASON', 'DATE', 'TEAM', 'OPPONENT', 'HOME/AWAY', 'RESULT',
       'MIN', 'PTS', 'FGM', 'FGA', 'FG_PCT', '3PM', '3PA', '3P_PCT', 'FTM',
       'FTA', 'FT_PCT', 'OREB', 'DREB', 'REB', 'AST', 'STL', 'BLK', 'TOV',
       'PF', 'PlusMinus'],
      dtype='str')

In [19]:
len(df)

327

In [20]:
df["TEAM"].unique()

<StringArray>
['WAS', 'PHO', 'NYL']
Length: 3, dtype: str

In [21]:
df.groupby("SEASON").size()

SEASON
2015    34
2016    31
2017    24
2018    27
2019    34
2021    27
2022    34
2023    37
2024    38
2025    41
dtype: int64

In [22]:
sorted(df["SEASON"].unique())

[np.int64(2015),
 np.int64(2016),
 np.int64(2017),
 np.int64(2018),
 np.int64(2019),
 np.int64(2021),
 np.int64(2022),
 np.int64(2023),
 np.int64(2024),
 np.int64(2025)]

In [23]:
df.describe()

,SEASON,MIN,PTS,FGM,FGA,FG_PCT,3PM,3PA,3P_PCT,FTM,...,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PlusMinus
count,327.000000,327.000000,327.000000,327.000000,327.000000,327.000000,327.000000,327.000000,327.000000,327.000000,...,327.000000,327.000000,327.000000,327.000000,327.000000,327.000000,327.000000,327.000000,327.000000,327.000000
mean,2020.333333,28.290520,8.755352,3.024465,7.743119,37.393272,1.012232,3.229358,27.352599,1.694190,...,50.524771,0.308869,2.993884,3.302752,5.299694,1.039755,0.247706,2.033639,2.195719,1.752294
std,3.412655,7.063125,5.752681,2.094255,3.802817,18.933126,1.121391,2.107391,29.282335,1.895603,...,44.324933,0.547735,1.761890,1.824364,2.769593,1.015951,0.550894,1.517414,1.420138,12.886115
min,2015.000000,9.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-28.000000
25%,2017.000000,24.000000,5.000000,1.000000,5.000000,25.000000,0.000000,2.000000,0.000000,0.000000,...,0.000000,0.000000,2.000000,2.000000,3.000000,0.000000,0.000000,1.000000,1.000000,-7.000000
50%,2021.000000,30.000000,8.000000,3.000000,7.000000,37.500000,1.000000,3.000000,25.000000,1.000000,...,50.000000,0.000000,3.000000,3.000000,5.000000,1.000000,0.000000,2.000000,2.000000,1.000000
75%,2023.000000,34.000000,12.000000,4.000000,10.000000,50.000000,2.000000,5.000000,50.000000,3.000000,...,100.000000,1.000000,4.000000,4.000000,7.000000,2.000000,0.000000,3.000000,3.000000,10.500000
max,2025.000000,44.000000,31.000000,10.000000,21.000000,100.000000,5.000000,11.000000,100.000000,10.000000,...,100.000000,3.000000,9.000000,9.000000,15.000000,6.000000,3.000000,8.000000,6.000000,44.000000